const float ABS_DELTA = 0.0001;
const int ABS_NUM_SAMPLES_PER_EDGE = 15;
const int ABS_MAX_SUBDIVISION_STEPS = 3;
const int REVERSE_SAMPLING_NUM_SAMPLES_ALONG_EDGE = 5;
#define REVERSE_SAMPLING_METHOD 2
#define SET_TYPE 1
