const float ABS_DELTA = 0.001;
const int ABS_NUM_SAMPLES_PER_EDGE = 40;
const int REVERSE_SAMPLING_NUM_SAMPLES_ALONG_EDGE = 20;
const int REVERSE_SAMPLING_HALTON_NUM_HALTON_SAMPLES = 20;
#define SET_TYPE 0
