const float ABS_DELTA = 0.01;
const int ABS_NUM_SAMPLES_PER_EDGE = 40;
const int ABS_MAX_SUBDIVISION_STEPS = 1;
const int REVERSE_SAMPLING_NUM_SAMPLES_ALONG_EDGE = 20;
#define REVERSE_SAMPLING_METHOD 2
#define SET_TYPE 0
#define NIRENSTEIN_USE_MULTI_VIEW_RENDERING
#define USE_HYBRID_VISIBILITY_SAMPLING
