#version 460

#include "rt/defines.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(binding = 0, set = 0) uniform sampler2D framebuffer;
layout(binding = 1, set = 0) writeonly buffer errorBuffer {
    uint error;
};

void main() {
    vec3 color = texelFetch(framebuffer, ivec2(gl_GlobalInvocationID.xy), 0).xyz;
    if (color == vec3(1.0f, 0.0f, 0.0f)) {
        atomicAdd(error, 1);
    }
}
